### ISSUE TITLE
Assignment 6-3 - Blog Tags

### ISSUE THREAD

**Issue by ambethia** [cateia97/assignments#29]
# Week 6 - Day 2

We're going to continue making a blog app.
- [x] Create a `Tag` model, it will probably have a `name`.
- [x] Create a `Tagging` model, it will have post and tag references.
- [x] Setup the many-to-many relationship between `Post` and `Tag`
- [x] The user should be able to add tags to a post when editing it (can be done a few ways, google will help you here, see how others solve this very same common problem)
- [x] The visitor facing post page should show a list of tags that a post was tagged with.
- [ ] _Bonus_: Make the listed tags from the previous feature link to a list of blog posts that have that tag.

**Comment by bristolkr** [comment]
https://nameless-woodland-3754.herokuapp.com/ (ongoing)
and repo: https://github.com/cateia97/blog_app

I finally figured out why my fonts weren't loading, so now the CSS is actually loading. :)

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/IUu7swWWXfeyk/200w_d.gif)
